_wandb:
    value:
        cli_version: 0.23.0
        e:
            v7vjo33xlwx5hd5r6vdh86iqyo7s2pxs:
                args:
                    - --config
                    - configs/config_offline_sac.yaml
                codePath: train_offline_sac.py
                codePathLocal: train_offline_sac.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "32212254720"
                        used: "24112721920"
                email: chengyon23@mails.tsinghua.edu.cn
                executable: /root/miniconda3/envs/rl/bin/python
                git:
                    commit: cb4cb3d86eefe77c2ef7641de4eb2a6bc1267a48
                    remote: https://github.com/chengjt23/RL_generals_bots.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-63c94b1b-0227-3332-779c-90bc491f56aa
                host: p-acf455511d83-ackcs-00gjftw7
                memory:
                    total: "1081819086848"
                os: Linux-5.15.0-119-generic-x86_64-with-glibc2.39
                program: /root/RL_generals_bots/train_offline_sac.py
                python: CPython 3.11.14
                root: /root/RL_generals_bots
                startedAt: "2025-12-12T08:29:49.410311Z"
                writerId: v7vjo33xlwx5hd5r6vdh86iqyo7s2pxs
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.11.14
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
data:
    value:
        data_dir: data/generals_io_replays
        max_replays: null
        min_stars: 70
        num_workers: 4
experiment:
    value:
        bc_pretrain_path: ./experiments/epoch_12_loss_1.6968.pt
        name: offline_sac
        save_dir: experiments
logging:
    value:
        project_name: generals-offline-rl
        use_wandb: true
        wandb_entity: null
model:
    value:
        base_channels: 64
        grid_size: 24
        memory_channels: 18
        obs_channels: 15
training:
    value:
        actor_lr: 0.0001
        alpha: 0.2
        alpha_lr: 0.0001
        auto_tune_alpha: true
        batch_size: 128
        critic_lr: 0.0001
        device: cuda
        epochs: 10
        gamma: 0.99
        log_frequency: 100
        save_frequency: 2
        seed: 42
        tau: 0.005
